/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "base_types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ic_base_types_pb_v1_PrincipalId, ic_base_types_pb_v1_PrincipalId, AUTO)





