/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "base_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ic_base_types_pb_v1_PrincipalId, ic_base_types_pb_v1_PrincipalId, AUTO)


PB_BIND(ic_base_types_pb_v1_CanisterId, ic_base_types_pb_v1_CanisterId, AUTO)


PB_BIND(ic_base_types_pb_v1_NeuronId, ic_base_types_pb_v1_NeuronId, AUTO)


PB_BIND(ic_base_types_pb_v1_ProposalId, ic_base_types_pb_v1_ProposalId, AUTO)


PB_BIND(ic_base_types_pb_v1_MethodAuthzInfo, ic_base_types_pb_v1_MethodAuthzInfo, AUTO)


PB_BIND(ic_base_types_pb_v1_CanisterAuthzInfo, ic_base_types_pb_v1_CanisterAuthzInfo, AUTO)





