/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "common_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ic_nns_common_pb_v1_CanisterId, ic_nns_common_pb_v1_CanisterId, AUTO)


PB_BIND(ic_nns_common_pb_v1_NeuronId, ic_nns_common_pb_v1_NeuronId, AUTO)


PB_BIND(ic_nns_common_pb_v1_ProposalId, ic_nns_common_pb_v1_ProposalId, AUTO)


PB_BIND(ic_nns_common_pb_v1_MethodAuthzInfo, ic_nns_common_pb_v1_MethodAuthzInfo, AUTO)


PB_BIND(ic_nns_common_pb_v1_CanisterAuthzInfo, ic_nns_common_pb_v1_CanisterAuthzInfo, AUTO)



