/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_APP_SRC_PROTOBUF_DFINITY_PB_H_INCLUDED
#define PB_APP_SRC_PROTOBUF_DFINITY_PB_H_INCLUDED

#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AccountIdentifier {
    pb_byte_t hash[32]; /* always 32 bytes, starts with CRC32 */
} AccountIdentifier;

typedef struct _BlockHeight {
    uint64_t height;
} BlockHeight;

typedef struct _ICPTs {
    uint64_t doms;
} ICPTs;

typedef struct _Memo {
    uint64_t memo;
} Memo;

typedef struct _Subaccount {
    pb_byte_t sub_account[32]; /* always 32 bytes */
} Subaccount;

typedef struct _Payment {
    pb_size_t which_payment_type;
    union {
        ICPTs reciever_gets;
    } payment_type;
} Payment;

typedef struct _SendRequest {
    bool has_memo;
    Memo memo; /* required */
    bool has_payment;
    Payment payment; /* required */
    bool has_max_fee;
    ICPTs max_fee; /* required */
    bool has_from_subaccount;
    Subaccount from_subaccount; /* optional */
    bool has_to;
    AccountIdentifier to; /* required */
    bool has_created_at;
    BlockHeight created_at; /* optional */
} SendRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Memo_init_default                        {0}
#define ICPTs_init_default                       {0}
#define Payment_init_default                     {0, {ICPTs_init_default}}
#define Subaccount_init_default                  {{0}}
#define AccountIdentifier_init_default           {{0}}
#define BlockHeight_init_default                 {0}
#define SendRequest_init_default                 {false, Memo_init_default, false, Payment_init_default, false, ICPTs_init_default, false, Subaccount_init_default, false, AccountIdentifier_init_default, false, BlockHeight_init_default}
#define Memo_init_zero                           {0}
#define ICPTs_init_zero                          {0}
#define Payment_init_zero                        {0, {ICPTs_init_zero}}
#define Subaccount_init_zero                     {{0}}
#define AccountIdentifier_init_zero              {{0}}
#define BlockHeight_init_zero                    {0}
#define SendRequest_init_zero                    {false, Memo_init_zero, false, Payment_init_zero, false, ICPTs_init_zero, false, Subaccount_init_zero, false, AccountIdentifier_init_zero, false, BlockHeight_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AccountIdentifier_hash_tag               1
#define BlockHeight_height_tag                   1
#define ICPTs_doms_tag                           1
#define Memo_memo_tag                            1
#define Subaccount_sub_account_tag               1
#define Payment_reciever_gets_tag                1
#define SendRequest_memo_tag                     1
#define SendRequest_payment_tag                  2
#define SendRequest_max_fee_tag                  3
#define SendRequest_from_subaccount_tag          4
#define SendRequest_to_tag                       5
#define SendRequest_created_at_tag               6

/* Struct field encoding specification for nanopb */
#define Memo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   memo,              1)
#define Memo_CALLBACK NULL
#define Memo_DEFAULT NULL

#define ICPTs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   doms,              1)
#define ICPTs_CALLBACK NULL
#define ICPTs_DEFAULT NULL

#define Payment_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payment_type,reciever_gets,payment_type.reciever_gets),   1)
#define Payment_CALLBACK NULL
#define Payment_DEFAULT NULL
#define Payment_payment_type_reciever_gets_MSGTYPE ICPTs

#define Subaccount_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, sub_account,       1)
#define Subaccount_CALLBACK NULL
#define Subaccount_DEFAULT NULL

#define AccountIdentifier_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, hash,              1)
#define AccountIdentifier_CALLBACK NULL
#define AccountIdentifier_DEFAULT NULL

#define BlockHeight_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   height,            1)
#define BlockHeight_CALLBACK NULL
#define BlockHeight_DEFAULT NULL

#define SendRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memo,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payment,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_fee,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_subaccount,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        6)
#define SendRequest_CALLBACK NULL
#define SendRequest_DEFAULT NULL
#define SendRequest_memo_MSGTYPE Memo
#define SendRequest_payment_MSGTYPE Payment
#define SendRequest_max_fee_MSGTYPE ICPTs
#define SendRequest_from_subaccount_MSGTYPE Subaccount
#define SendRequest_to_MSGTYPE AccountIdentifier
#define SendRequest_created_at_MSGTYPE BlockHeight

extern const pb_msgdesc_t Memo_msg;
extern const pb_msgdesc_t ICPTs_msg;
extern const pb_msgdesc_t Payment_msg;
extern const pb_msgdesc_t Subaccount_msg;
extern const pb_msgdesc_t AccountIdentifier_msg;
extern const pb_msgdesc_t BlockHeight_msg;
extern const pb_msgdesc_t SendRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Memo_fields &Memo_msg
#define ICPTs_fields &ICPTs_msg
#define Payment_fields &Payment_msg
#define Subaccount_fields &Subaccount_msg
#define AccountIdentifier_fields &AccountIdentifier_msg
#define BlockHeight_fields &BlockHeight_msg
#define SendRequest_fields &SendRequest_msg

/* Maximum encoded size of messages (where known) */
#define AccountIdentifier_size                   34
#define BlockHeight_size                         11
#define ICPTs_size                               11
#define Memo_size                                11
#define Payment_size                             13
#define SendRequest_size                         126
#define Subaccount_size                          34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
