/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "dfinity.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Memo, Memo, AUTO
)


PB_BIND(ICPTs, ICPTs, AUTO
)


PB_BIND(Payment, Payment, AUTO
)


PB_BIND(Subaccount, Subaccount, AUTO
)


PB_BIND(AccountIdentifier, AccountIdentifier, AUTO
)


PB_BIND(BlockHeight, BlockHeight, AUTO
)


PB_BIND(SendRequest, SendRequest, AUTO
)



