/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_DFINITY_PB_H_INCLUDED
#define PB_DFINITY_PB_H_INCLUDED
#include <pb.h>
#include "base_types.pb.h"
#include "governance.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AccountIdentifier { 
    pb_byte_t hash[32]; /* always 32 bytes, starts with CRC32 */
} AccountIdentifier;

typedef struct _BlockHeight { 
    uint64_t height; 
} BlockHeight;

typedef struct _ICPTs { 
    uint64_t e8s; 
} ICPTs;

typedef struct _ManageNeuronPb { 
    bool has_manage_neuron;
    ic_nns_governance_pb_v1_ManageNeuron manage_neuron; 
} ManageNeuronPb;

typedef struct _Memo { 
    uint64_t memo; 
} Memo;

typedef struct _Subaccount { 
    pb_byte_t sub_account[32]; /* always 32 bytes */
} Subaccount;

typedef struct _TimeStamp { 
    uint64_t timestamp_nanos; 
} TimeStamp;

typedef struct _Payment { 
    bool has_receiver_gets;
    ICPTs receiver_gets; 
} Payment;

typedef struct _SendRequest { 
    bool has_memo;
    Memo memo; /* required */
    bool has_payment;
    Payment payment; /* required */
    bool has_max_fee;
    ICPTs max_fee; /* required */
    bool has_from_subaccount;
    Subaccount from_subaccount; /* optional */
    bool has_to;
    AccountIdentifier to; /* required */
    bool has_created_at;
    BlockHeight created_at; /* optional */
    bool has_created_at_time;
    TimeStamp created_at_time; /* optional */
} SendRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TimeStamp_init_default                   {0}
#define Memo_init_default                        {0}
#define ICPTs_init_default                       {0}
#define Payment_init_default                     {false, ICPTs_init_default}
#define Subaccount_init_default                  {{0}}
#define AccountIdentifier_init_default           {{0}}
#define BlockHeight_init_default                 {0}
#define SendRequest_init_default                 {false, Memo_init_default, false, Payment_init_default, false, ICPTs_init_default, false, Subaccount_init_default, false, AccountIdentifier_init_default, false, BlockHeight_init_default, false, TimeStamp_init_default}
#define ManageNeuronPb_init_default              {false, ic_nns_governance_pb_v1_ManageNeuron_init_default}
#define TimeStamp_init_zero                      {0}
#define Memo_init_zero                           {0}
#define ICPTs_init_zero                          {0}
#define Payment_init_zero                        {false, ICPTs_init_zero}
#define Subaccount_init_zero                     {{0}}
#define AccountIdentifier_init_zero              {{0}}
#define BlockHeight_init_zero                    {0}
#define SendRequest_init_zero                    {false, Memo_init_zero, false, Payment_init_zero, false, ICPTs_init_zero, false, Subaccount_init_zero, false, AccountIdentifier_init_zero, false, BlockHeight_init_zero, false, TimeStamp_init_zero}
#define ManageNeuronPb_init_zero                 {false, ic_nns_governance_pb_v1_ManageNeuron_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define AccountIdentifier_hash_tag               1
#define BlockHeight_height_tag                   1
#define ICPTs_e8s_tag                            1
#define ManageNeuronPb_manage_neuron_tag         1
#define Memo_memo_tag                            1
#define Subaccount_sub_account_tag               1
#define TimeStamp_timestamp_nanos_tag            1
#define Payment_receiver_gets_tag                1
#define SendRequest_memo_tag                     1
#define SendRequest_payment_tag                  2
#define SendRequest_max_fee_tag                  3
#define SendRequest_from_subaccount_tag          4
#define SendRequest_to_tag                       5
#define SendRequest_created_at_tag               6
#define SendRequest_created_at_time_tag          7

/* Struct field encoding specification for nanopb */
#define TimeStamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_nanos,   1)
#define TimeStamp_CALLBACK NULL
#define TimeStamp_DEFAULT NULL

#define Memo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   memo,              1)
#define Memo_CALLBACK NULL
#define Memo_DEFAULT NULL

#define ICPTs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   e8s,               1)
#define ICPTs_CALLBACK NULL
#define ICPTs_DEFAULT NULL

#define Payment_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver_gets,     1)
#define Payment_CALLBACK NULL
#define Payment_DEFAULT NULL
#define Payment_receiver_gets_MSGTYPE ICPTs

#define Subaccount_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, sub_account,       1)
#define Subaccount_CALLBACK NULL
#define Subaccount_DEFAULT NULL

#define AccountIdentifier_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, hash,              1)
#define AccountIdentifier_CALLBACK NULL
#define AccountIdentifier_DEFAULT NULL

#define BlockHeight_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   height,            1)
#define BlockHeight_CALLBACK NULL
#define BlockHeight_DEFAULT NULL

#define SendRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memo,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payment,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_fee,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_subaccount,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at_time,   7)
#define SendRequest_CALLBACK NULL
#define SendRequest_DEFAULT NULL
#define SendRequest_memo_MSGTYPE Memo
#define SendRequest_payment_MSGTYPE Payment
#define SendRequest_max_fee_MSGTYPE ICPTs
#define SendRequest_from_subaccount_MSGTYPE Subaccount
#define SendRequest_to_MSGTYPE AccountIdentifier
#define SendRequest_created_at_MSGTYPE BlockHeight
#define SendRequest_created_at_time_MSGTYPE TimeStamp

#define ManageNeuronPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  manage_neuron,     1)
#define ManageNeuronPb_CALLBACK NULL
#define ManageNeuronPb_DEFAULT NULL
#define ManageNeuronPb_manage_neuron_MSGTYPE ic_nns_governance_pb_v1_ManageNeuron

extern const pb_msgdesc_t TimeStamp_msg;
extern const pb_msgdesc_t Memo_msg;
extern const pb_msgdesc_t ICPTs_msg;
extern const pb_msgdesc_t Payment_msg;
extern const pb_msgdesc_t Subaccount_msg;
extern const pb_msgdesc_t AccountIdentifier_msg;
extern const pb_msgdesc_t BlockHeight_msg;
extern const pb_msgdesc_t SendRequest_msg;
extern const pb_msgdesc_t ManageNeuronPb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TimeStamp_fields &TimeStamp_msg
#define Memo_fields &Memo_msg
#define ICPTs_fields &ICPTs_msg
#define Payment_fields &Payment_msg
#define Subaccount_fields &Subaccount_msg
#define AccountIdentifier_fields &AccountIdentifier_msg
#define BlockHeight_fields &BlockHeight_msg
#define SendRequest_fields &SendRequest_msg
#define ManageNeuronPb_fields &ManageNeuronPb_msg

/* Maximum encoded size of messages (where known) */
#define AccountIdentifier_size                   34
#define BlockHeight_size                         11
#define ICPTs_size                               11
#define Memo_size                                11
#define Payment_size                             13
#define SendRequest_size                         139
#define Subaccount_size                          34
#define TimeStamp_size                           11
#if defined(ic_nns_governance_pb_v1_ManageNeuron_size)
#define ManageNeuronPb_size                      (6 + ic_nns_governance_pb_v1_ManageNeuron_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
