/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ic_ledger_pb_v1_LedgerInit, ic_ledger_pb_v1_LedgerInit, AUTO)

PB_BIND(ic_ledger_pb_v1_LedgerUpgrade, ic_ledger_pb_v1_LedgerUpgrade, AUTO)

PB_BIND(ic_ledger_pb_v1_SendRequest, ic_ledger_pb_v1_SendRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_SendResponse, ic_ledger_pb_v1_SendResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_NotifyRequest, ic_ledger_pb_v1_NotifyRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_NotifyResponse, ic_ledger_pb_v1_NotifyResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_TransactionNotificationRequest, ic_ledger_pb_v1_TransactionNotificationRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_TransactionNotificationResponse, ic_ledger_pb_v1_TransactionNotificationResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_CyclesNotificationResponse, ic_ledger_pb_v1_CyclesNotificationResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_AccountBalanceRequest, ic_ledger_pb_v1_AccountBalanceRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_AccountBalanceResponse, ic_ledger_pb_v1_AccountBalanceResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_TipOfChainRequest, ic_ledger_pb_v1_TipOfChainRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_TipOfChainResponse, ic_ledger_pb_v1_TipOfChainResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_TotalSupplyRequest, ic_ledger_pb_v1_TotalSupplyRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_TotalSupplyResponse, ic_ledger_pb_v1_TotalSupplyResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_LedgerArchiveRequest, ic_ledger_pb_v1_LedgerArchiveRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_BlockRequest, ic_ledger_pb_v1_BlockRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_EncodedBlock, ic_ledger_pb_v1_EncodedBlock, AUTO)

PB_BIND(ic_ledger_pb_v1_BlockResponse, ic_ledger_pb_v1_BlockResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_GetBlocksRequest, ic_ledger_pb_v1_GetBlocksRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_Refund, ic_ledger_pb_v1_Refund, AUTO)

PB_BIND(ic_ledger_pb_v1_ToppedUp, ic_ledger_pb_v1_ToppedUp, AUTO)

PB_BIND(ic_ledger_pb_v1_EncodedBlocks, ic_ledger_pb_v1_EncodedBlocks, AUTO)

PB_BIND(ic_ledger_pb_v1_GetBlocksResponse, ic_ledger_pb_v1_GetBlocksResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_IterBlocksRequest, ic_ledger_pb_v1_IterBlocksRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_IterBlocksResponse, ic_ledger_pb_v1_IterBlocksResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_ArchiveIndexEntry, ic_ledger_pb_v1_ArchiveIndexEntry, AUTO)

PB_BIND(ic_ledger_pb_v1_ArchiveIndexResponse, ic_ledger_pb_v1_ArchiveIndexResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_ArchiveInit, ic_ledger_pb_v1_ArchiveInit, AUTO)

PB_BIND(ic_ledger_pb_v1_ArchiveAddRequest, ic_ledger_pb_v1_ArchiveAddRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_ArchiveAddResponse, ic_ledger_pb_v1_ArchiveAddResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_GetNodesRequest, ic_ledger_pb_v1_GetNodesRequest, AUTO)

PB_BIND(ic_ledger_pb_v1_GetNodesResponse, ic_ledger_pb_v1_GetNodesResponse, AUTO)

PB_BIND(ic_ledger_pb_v1_ICPTs, ic_ledger_pb_v1_ICPTs, AUTO)

PB_BIND(ic_ledger_pb_v1_Payment, ic_ledger_pb_v1_Payment, AUTO)

PB_BIND(ic_ledger_pb_v1_BlockHeight, ic_ledger_pb_v1_BlockHeight, AUTO)

PB_BIND(ic_ledger_pb_v1_Block, ic_ledger_pb_v1_Block, AUTO)

PB_BIND(ic_ledger_pb_v1_Hash, ic_ledger_pb_v1_Hash, AUTO)

PB_BIND(ic_ledger_pb_v1_Account, ic_ledger_pb_v1_Account, AUTO)

PB_BIND(ic_ledger_pb_v1_Transaction, ic_ledger_pb_v1_Transaction, AUTO)

PB_BIND(ic_ledger_pb_v1_Send, ic_ledger_pb_v1_Send, AUTO)

PB_BIND(ic_ledger_pb_v1_Mint, ic_ledger_pb_v1_Mint, AUTO)

PB_BIND(ic_ledger_pb_v1_Burn, ic_ledger_pb_v1_Burn, AUTO)

PB_BIND(ic_ledger_pb_v1_AccountIdentifier, ic_ledger_pb_v1_AccountIdentifier, AUTO)

PB_BIND(ic_ledger_pb_v1_Subaccount, ic_ledger_pb_v1_Subaccount, AUTO)

PB_BIND(ic_ledger_pb_v1_Memo, ic_ledger_pb_v1_Memo, AUTO)

PB_BIND(ic_ledger_pb_v1_TimeStamp, ic_ledger_pb_v1_TimeStamp, AUTO)

PB_BIND(ic_ledger_pb_v1_Certification, ic_ledger_pb_v1_Certification, AUTO)
