/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_IC_LEDGER_PB_V1_TYPES_PB_H_INCLUDED
#define PB_IC_LEDGER_PB_V1_TYPES_PB_H_INCLUDED
#include <pb.h>
#include "base_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ic_ledger_pb_v1_AccountIdentifier { 
    pb_callback_t hash; 
} ic_ledger_pb_v1_AccountIdentifier;

/* Add blocks to the archive canister */
typedef struct _ic_ledger_pb_v1_ArchiveAddRequest { 
    pb_callback_t blocks; 
} ic_ledger_pb_v1_ArchiveAddRequest;

typedef struct _ic_ledger_pb_v1_ArchiveAddResponse { 
    char dummy_field;
} ic_ledger_pb_v1_ArchiveAddResponse;

typedef struct _ic_ledger_pb_v1_ArchiveIndexResponse { 
    pb_callback_t entries; 
} ic_ledger_pb_v1_ArchiveIndexResponse;

typedef struct _ic_ledger_pb_v1_Certification { 
    pb_callback_t certification; 
} ic_ledger_pb_v1_Certification;

typedef struct _ic_ledger_pb_v1_EncodedBlock { 
    pb_callback_t block; 
} ic_ledger_pb_v1_EncodedBlock;

typedef struct _ic_ledger_pb_v1_EncodedBlocks { 
    pb_callback_t blocks; 
} ic_ledger_pb_v1_EncodedBlocks;

/* Fetch a list of all of the archive nodes */
typedef struct _ic_ledger_pb_v1_GetNodesRequest { 
    char dummy_field;
} ic_ledger_pb_v1_GetNodesRequest;

typedef struct _ic_ledger_pb_v1_GetNodesResponse { 
    pb_callback_t nodes; 
} ic_ledger_pb_v1_GetNodesResponse;

typedef struct _ic_ledger_pb_v1_Hash { 
    pb_callback_t hash; 
} ic_ledger_pb_v1_Hash;

typedef struct _ic_ledger_pb_v1_IterBlocksResponse { 
    pb_callback_t blocks; 
} ic_ledger_pb_v1_IterBlocksResponse;

/* The format of values serialized to/from the stable memory during and upgrade */
typedef struct _ic_ledger_pb_v1_LedgerUpgrade { 
    char dummy_field;
} ic_ledger_pb_v1_LedgerUpgrade;

typedef struct _ic_ledger_pb_v1_NotifyResponse { 
    char dummy_field;
} ic_ledger_pb_v1_NotifyResponse;

typedef struct _ic_ledger_pb_v1_Subaccount { 
    pb_callback_t sub_account; 
} ic_ledger_pb_v1_Subaccount;

/* Get the length of the chain with a certification */
typedef struct _ic_ledger_pb_v1_TipOfChainRequest { 
    char dummy_field;
} ic_ledger_pb_v1_TipOfChainRequest;

typedef struct _ic_ledger_pb_v1_ToppedUp { 
    char dummy_field;
} ic_ledger_pb_v1_ToppedUp;

/* How many ICPTs are there not in the minting account */
typedef struct _ic_ledger_pb_v1_TotalSupplyRequest { 
    char dummy_field;
} ic_ledger_pb_v1_TotalSupplyRequest;

typedef struct _ic_ledger_pb_v1_TransactionNotificationResponse { 
    pb_callback_t response; 
} ic_ledger_pb_v1_TransactionNotificationResponse;

/* Get the balance of an account */
typedef struct _ic_ledger_pb_v1_AccountBalanceRequest { 
    bool has_account;
    ic_ledger_pb_v1_AccountIdentifier account; 
} ic_ledger_pb_v1_AccountBalanceRequest;

typedef struct _ic_ledger_pb_v1_ArchiveIndexEntry { 
    uint64_t height_from; 
    uint64_t height_to; 
    bool has_canister_id;
    ic_base_types_pb_v1_PrincipalId canister_id; 
} ic_ledger_pb_v1_ArchiveIndexEntry;

/* * Archive canister *
 Init the archive canister */
typedef struct _ic_ledger_pb_v1_ArchiveInit { 
    uint32_t node_max_memory_size_bytes; 
    uint32_t max_message_size_bytes; 
} ic_ledger_pb_v1_ArchiveInit;

typedef struct _ic_ledger_pb_v1_BlockHeight { 
    uint64_t height; 
} ic_ledger_pb_v1_BlockHeight;

/* Get a single block */
typedef struct _ic_ledger_pb_v1_BlockRequest { 
    uint64_t block_height; 
} ic_ledger_pb_v1_BlockRequest;

typedef struct _ic_ledger_pb_v1_BlockResponse { 
    pb_size_t which_block_content;
    union {
        ic_ledger_pb_v1_EncodedBlock block;
        ic_base_types_pb_v1_PrincipalId canister_id;
    } block_content; 
} ic_ledger_pb_v1_BlockResponse;

/* Get a set of blocks */
typedef struct _ic_ledger_pb_v1_GetBlocksRequest { 
    uint64_t start; 
    uint64_t length; 
} ic_ledger_pb_v1_GetBlocksRequest;

typedef struct _ic_ledger_pb_v1_GetBlocksResponse { 
    pb_size_t which_get_blocks_content;
    union {
        ic_ledger_pb_v1_EncodedBlocks blocks;
        pb_callback_t error;
    } get_blocks_content; 
} ic_ledger_pb_v1_GetBlocksResponse;

/* ** BASIC TYPES ** */
typedef struct _ic_ledger_pb_v1_ICPTs { 
    uint64_t e8s; 
} ic_ledger_pb_v1_ICPTs;

/* Iterate through blocks */
typedef struct _ic_ledger_pb_v1_IterBlocksRequest { 
    uint64_t start; 
    uint64_t length; 
} ic_ledger_pb_v1_IterBlocksRequest;

/* Initialise the ledger canister */
typedef struct _ic_ledger_pb_v1_LedgerInit { 
    bool has_minting_account;
    ic_ledger_pb_v1_AccountIdentifier minting_account; 
    pb_callback_t initial_values; 
    bool has_archive_canister;
    ic_base_types_pb_v1_PrincipalId archive_canister; 
    uint32_t max_message_size_bytes; 
} ic_ledger_pb_v1_LedgerInit;

typedef struct _ic_ledger_pb_v1_Memo { 
    uint64_t memo; 
} ic_ledger_pb_v1_Memo;

typedef struct _ic_ledger_pb_v1_TimeStamp { 
    uint64_t timestamp_nanos; 
} ic_ledger_pb_v1_TimeStamp;

typedef struct _ic_ledger_pb_v1_Account { 
    bool has_identifier;
    ic_ledger_pb_v1_AccountIdentifier identifier; 
    bool has_balance;
    ic_ledger_pb_v1_ICPTs balance; 
} ic_ledger_pb_v1_Account;

typedef struct _ic_ledger_pb_v1_AccountBalanceResponse { 
    bool has_balance;
    ic_ledger_pb_v1_ICPTs balance; 
} ic_ledger_pb_v1_AccountBalanceResponse;

typedef struct _ic_ledger_pb_v1_Burn { 
    bool has_from;
    ic_ledger_pb_v1_AccountIdentifier from; 
    bool has_amount;
    ic_ledger_pb_v1_ICPTs amount; 
} ic_ledger_pb_v1_Burn;

/* Archive any blocks older than this */
typedef struct _ic_ledger_pb_v1_LedgerArchiveRequest { 
    bool has_timestamp;
    ic_ledger_pb_v1_TimeStamp timestamp; 
} ic_ledger_pb_v1_LedgerArchiveRequest;

typedef struct _ic_ledger_pb_v1_Mint { 
    bool has_to;
    ic_ledger_pb_v1_AccountIdentifier to; 
    bool has_amount;
    ic_ledger_pb_v1_ICPTs amount; 
} ic_ledger_pb_v1_Mint;

/* Notify a canister that it has received a payment */
typedef struct _ic_ledger_pb_v1_NotifyRequest { 
    bool has_block_height;
    ic_ledger_pb_v1_BlockHeight block_height; 
    bool has_max_fee;
    ic_ledger_pb_v1_ICPTs max_fee; 
    bool has_from_subaccount;
    ic_ledger_pb_v1_Subaccount from_subaccount; 
    bool has_to_canister;
    ic_base_types_pb_v1_PrincipalId to_canister; 
    bool has_to_subaccount;
    ic_ledger_pb_v1_Subaccount to_subaccount; 
} ic_ledger_pb_v1_NotifyRequest;

typedef struct _ic_ledger_pb_v1_Payment { 
    bool has_receiver_gets;
    ic_ledger_pb_v1_ICPTs receiver_gets; 
} ic_ledger_pb_v1_Payment;

typedef struct _ic_ledger_pb_v1_Refund { 
    bool has_refund;
    ic_ledger_pb_v1_BlockHeight refund; 
    pb_callback_t error; 
} ic_ledger_pb_v1_Refund;

typedef struct _ic_ledger_pb_v1_Send { 
    bool has_from;
    ic_ledger_pb_v1_AccountIdentifier from; 
    bool has_to;
    ic_ledger_pb_v1_AccountIdentifier to; 
    bool has_amount;
    ic_ledger_pb_v1_ICPTs amount; 
    bool has_max_fee;
    ic_ledger_pb_v1_ICPTs max_fee; 
} ic_ledger_pb_v1_Send;

typedef struct _ic_ledger_pb_v1_SendResponse { 
    bool has_resulting_height;
    ic_ledger_pb_v1_BlockHeight resulting_height; 
} ic_ledger_pb_v1_SendResponse;

typedef struct _ic_ledger_pb_v1_TipOfChainResponse { 
    bool has_certification;
    ic_ledger_pb_v1_Certification certification; 
    bool has_chain_length;
    ic_ledger_pb_v1_BlockHeight chain_length; 
} ic_ledger_pb_v1_TipOfChainResponse;

typedef struct _ic_ledger_pb_v1_TotalSupplyResponse { 
    bool has_total_supply;
    ic_ledger_pb_v1_ICPTs total_supply; 
} ic_ledger_pb_v1_TotalSupplyResponse;

typedef struct _ic_ledger_pb_v1_TransactionNotificationRequest { 
    bool has_from;
    ic_base_types_pb_v1_PrincipalId from; 
    bool has_from_subaccount;
    ic_ledger_pb_v1_Subaccount from_subaccount; 
    bool has_to;
    ic_base_types_pb_v1_PrincipalId to; 
    bool has_to_subaccount;
    ic_ledger_pb_v1_Subaccount to_subaccount; 
    bool has_block_height;
    ic_ledger_pb_v1_BlockHeight block_height; 
    bool has_amount;
    ic_ledger_pb_v1_ICPTs amount; 
    bool has_memo;
    ic_ledger_pb_v1_Memo memo; 
} ic_ledger_pb_v1_TransactionNotificationRequest;

typedef struct _ic_ledger_pb_v1_CyclesNotificationResponse { 
    pb_size_t which_response;
    union {
        ic_base_types_pb_v1_PrincipalId created_canister_id;
        ic_ledger_pb_v1_Refund refund;
        ic_ledger_pb_v1_ToppedUp topped_up;
    } response; 
} ic_ledger_pb_v1_CyclesNotificationResponse;

/* Make a payment */
typedef struct _ic_ledger_pb_v1_SendRequest { 
    bool has_memo;
    ic_ledger_pb_v1_Memo memo; 
    bool has_payment;
    ic_ledger_pb_v1_Payment payment; 
    bool has_max_fee;
    ic_ledger_pb_v1_ICPTs max_fee; 
    bool has_from_subaccount;
    ic_ledger_pb_v1_Subaccount from_subaccount; 
    bool has_to;
    ic_ledger_pb_v1_AccountIdentifier to; 
    bool has_created_at;
    ic_ledger_pb_v1_BlockHeight created_at; 
    bool has_created_at_time;
    ic_ledger_pb_v1_TimeStamp created_at_time; 
} ic_ledger_pb_v1_SendRequest;

typedef struct _ic_ledger_pb_v1_Transaction { 
    pb_size_t which_transfer;
    union {
        ic_ledger_pb_v1_Burn burn;
        ic_ledger_pb_v1_Mint mint;
        ic_ledger_pb_v1_Send send;
    } transfer; 
    bool has_memo;
    ic_ledger_pb_v1_Memo memo; 
    bool has_created_at;
    ic_ledger_pb_v1_BlockHeight created_at; 
    bool has_created_at_time;
    ic_ledger_pb_v1_TimeStamp created_at_time; 
} ic_ledger_pb_v1_Transaction;

/* This is the */
typedef struct _ic_ledger_pb_v1_Block { 
    bool has_parent_hash;
    ic_ledger_pb_v1_Hash parent_hash; 
    bool has_timestamp;
    ic_ledger_pb_v1_TimeStamp timestamp; 
    bool has_transaction;
    ic_ledger_pb_v1_Transaction transaction; 
} ic_ledger_pb_v1_Block;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ic_ledger_pb_v1_LedgerInit_init_default  {false, ic_ledger_pb_v1_AccountIdentifier_init_default, {{NULL}, NULL}, false, ic_base_types_pb_v1_PrincipalId_init_default, 0}
#define ic_ledger_pb_v1_LedgerUpgrade_init_default {0}
#define ic_ledger_pb_v1_SendRequest_init_default {false, ic_ledger_pb_v1_Memo_init_default, false, ic_ledger_pb_v1_Payment_init_default, false, ic_ledger_pb_v1_ICPTs_init_default, false, ic_ledger_pb_v1_Subaccount_init_default, false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_BlockHeight_init_default, false, ic_ledger_pb_v1_TimeStamp_init_default}
#define ic_ledger_pb_v1_SendResponse_init_default {false, ic_ledger_pb_v1_BlockHeight_init_default}
#define ic_ledger_pb_v1_NotifyRequest_init_default {false, ic_ledger_pb_v1_BlockHeight_init_default, false, ic_ledger_pb_v1_ICPTs_init_default, false, ic_ledger_pb_v1_Subaccount_init_default, false, ic_base_types_pb_v1_PrincipalId_init_default, false, ic_ledger_pb_v1_Subaccount_init_default}
#define ic_ledger_pb_v1_NotifyResponse_init_default {0}
#define ic_ledger_pb_v1_TransactionNotificationRequest_init_default {false, ic_base_types_pb_v1_PrincipalId_init_default, false, ic_ledger_pb_v1_Subaccount_init_default, false, ic_base_types_pb_v1_PrincipalId_init_default, false, ic_ledger_pb_v1_Subaccount_init_default, false, ic_ledger_pb_v1_BlockHeight_init_default, false, ic_ledger_pb_v1_ICPTs_init_default, false, ic_ledger_pb_v1_Memo_init_default}
#define ic_ledger_pb_v1_TransactionNotificationResponse_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_CyclesNotificationResponse_init_default {0, {ic_base_types_pb_v1_PrincipalId_init_default}}
#define ic_ledger_pb_v1_AccountBalanceRequest_init_default {false, ic_ledger_pb_v1_AccountIdentifier_init_default}
#define ic_ledger_pb_v1_AccountBalanceResponse_init_default {false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_TipOfChainRequest_init_default {0}
#define ic_ledger_pb_v1_TipOfChainResponse_init_default {false, ic_ledger_pb_v1_Certification_init_default, false, ic_ledger_pb_v1_BlockHeight_init_default}
#define ic_ledger_pb_v1_TotalSupplyRequest_init_default {0}
#define ic_ledger_pb_v1_TotalSupplyResponse_init_default {false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_LedgerArchiveRequest_init_default {false, ic_ledger_pb_v1_TimeStamp_init_default}
#define ic_ledger_pb_v1_BlockRequest_init_default {0}
#define ic_ledger_pb_v1_EncodedBlock_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_BlockResponse_init_default {0, {ic_ledger_pb_v1_EncodedBlock_init_default}}
#define ic_ledger_pb_v1_GetBlocksRequest_init_default {0, 0}
#define ic_ledger_pb_v1_Refund_init_default      {false, ic_ledger_pb_v1_BlockHeight_init_default, {{NULL}, NULL}}
#define ic_ledger_pb_v1_ToppedUp_init_default    {0}
#define ic_ledger_pb_v1_EncodedBlocks_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_GetBlocksResponse_init_default {0, {ic_ledger_pb_v1_EncodedBlocks_init_default}}
#define ic_ledger_pb_v1_IterBlocksRequest_init_default {0, 0}
#define ic_ledger_pb_v1_IterBlocksResponse_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveIndexEntry_init_default {0, 0, false, ic_base_types_pb_v1_PrincipalId_init_default}
#define ic_ledger_pb_v1_ArchiveIndexResponse_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveInit_init_default {0, 0}
#define ic_ledger_pb_v1_ArchiveAddRequest_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveAddResponse_init_default {0}
#define ic_ledger_pb_v1_GetNodesRequest_init_default {0}
#define ic_ledger_pb_v1_GetNodesResponse_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ICPTs_init_default       {0}
#define ic_ledger_pb_v1_Payment_init_default     {false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_BlockHeight_init_default {0}
#define ic_ledger_pb_v1_Block_init_default       {false, ic_ledger_pb_v1_Hash_init_default, false, ic_ledger_pb_v1_TimeStamp_init_default, false, ic_ledger_pb_v1_Transaction_init_default}
#define ic_ledger_pb_v1_Hash_init_default        {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Account_init_default     {false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_Transaction_init_default {0, {ic_ledger_pb_v1_Burn_init_default}, false, ic_ledger_pb_v1_Memo_init_default, false, ic_ledger_pb_v1_BlockHeight_init_default, false, ic_ledger_pb_v1_TimeStamp_init_default}
#define ic_ledger_pb_v1_Send_init_default        {false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_ICPTs_init_default, false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_Mint_init_default        {false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_Burn_init_default        {false, ic_ledger_pb_v1_AccountIdentifier_init_default, false, ic_ledger_pb_v1_ICPTs_init_default}
#define ic_ledger_pb_v1_AccountIdentifier_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Subaccount_init_default  {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Memo_init_default        {0}
#define ic_ledger_pb_v1_TimeStamp_init_default   {0}
#define ic_ledger_pb_v1_Certification_init_default {{{NULL}, NULL}}
#define ic_ledger_pb_v1_LedgerInit_init_zero     {false, ic_ledger_pb_v1_AccountIdentifier_init_zero, {{NULL}, NULL}, false, ic_base_types_pb_v1_PrincipalId_init_zero, 0}
#define ic_ledger_pb_v1_LedgerUpgrade_init_zero  {0}
#define ic_ledger_pb_v1_SendRequest_init_zero    {false, ic_ledger_pb_v1_Memo_init_zero, false, ic_ledger_pb_v1_Payment_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero, false, ic_ledger_pb_v1_Subaccount_init_zero, false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_BlockHeight_init_zero, false, ic_ledger_pb_v1_TimeStamp_init_zero}
#define ic_ledger_pb_v1_SendResponse_init_zero   {false, ic_ledger_pb_v1_BlockHeight_init_zero}
#define ic_ledger_pb_v1_NotifyRequest_init_zero  {false, ic_ledger_pb_v1_BlockHeight_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero, false, ic_ledger_pb_v1_Subaccount_init_zero, false, ic_base_types_pb_v1_PrincipalId_init_zero, false, ic_ledger_pb_v1_Subaccount_init_zero}
#define ic_ledger_pb_v1_NotifyResponse_init_zero {0}
#define ic_ledger_pb_v1_TransactionNotificationRequest_init_zero {false, ic_base_types_pb_v1_PrincipalId_init_zero, false, ic_ledger_pb_v1_Subaccount_init_zero, false, ic_base_types_pb_v1_PrincipalId_init_zero, false, ic_ledger_pb_v1_Subaccount_init_zero, false, ic_ledger_pb_v1_BlockHeight_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero, false, ic_ledger_pb_v1_Memo_init_zero}
#define ic_ledger_pb_v1_TransactionNotificationResponse_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_CyclesNotificationResponse_init_zero {0, {ic_base_types_pb_v1_PrincipalId_init_zero}}
#define ic_ledger_pb_v1_AccountBalanceRequest_init_zero {false, ic_ledger_pb_v1_AccountIdentifier_init_zero}
#define ic_ledger_pb_v1_AccountBalanceResponse_init_zero {false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_TipOfChainRequest_init_zero {0}
#define ic_ledger_pb_v1_TipOfChainResponse_init_zero {false, ic_ledger_pb_v1_Certification_init_zero, false, ic_ledger_pb_v1_BlockHeight_init_zero}
#define ic_ledger_pb_v1_TotalSupplyRequest_init_zero {0}
#define ic_ledger_pb_v1_TotalSupplyResponse_init_zero {false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_LedgerArchiveRequest_init_zero {false, ic_ledger_pb_v1_TimeStamp_init_zero}
#define ic_ledger_pb_v1_BlockRequest_init_zero   {0}
#define ic_ledger_pb_v1_EncodedBlock_init_zero   {{{NULL}, NULL}}
#define ic_ledger_pb_v1_BlockResponse_init_zero  {0, {ic_ledger_pb_v1_EncodedBlock_init_zero}}
#define ic_ledger_pb_v1_GetBlocksRequest_init_zero {0, 0}
#define ic_ledger_pb_v1_Refund_init_zero         {false, ic_ledger_pb_v1_BlockHeight_init_zero, {{NULL}, NULL}}
#define ic_ledger_pb_v1_ToppedUp_init_zero       {0}
#define ic_ledger_pb_v1_EncodedBlocks_init_zero  {{{NULL}, NULL}}
#define ic_ledger_pb_v1_GetBlocksResponse_init_zero {0, {ic_ledger_pb_v1_EncodedBlocks_init_zero}}
#define ic_ledger_pb_v1_IterBlocksRequest_init_zero {0, 0}
#define ic_ledger_pb_v1_IterBlocksResponse_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveIndexEntry_init_zero {0, 0, false, ic_base_types_pb_v1_PrincipalId_init_zero}
#define ic_ledger_pb_v1_ArchiveIndexResponse_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveInit_init_zero    {0, 0}
#define ic_ledger_pb_v1_ArchiveAddRequest_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ArchiveAddResponse_init_zero {0}
#define ic_ledger_pb_v1_GetNodesRequest_init_zero {0}
#define ic_ledger_pb_v1_GetNodesResponse_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_ICPTs_init_zero          {0}
#define ic_ledger_pb_v1_Payment_init_zero        {false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_BlockHeight_init_zero    {0}
#define ic_ledger_pb_v1_Block_init_zero          {false, ic_ledger_pb_v1_Hash_init_zero, false, ic_ledger_pb_v1_TimeStamp_init_zero, false, ic_ledger_pb_v1_Transaction_init_zero}
#define ic_ledger_pb_v1_Hash_init_zero           {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Account_init_zero        {false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_Transaction_init_zero    {0, {ic_ledger_pb_v1_Burn_init_zero}, false, ic_ledger_pb_v1_Memo_init_zero, false, ic_ledger_pb_v1_BlockHeight_init_zero, false, ic_ledger_pb_v1_TimeStamp_init_zero}
#define ic_ledger_pb_v1_Send_init_zero           {false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_Mint_init_zero           {false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_Burn_init_zero           {false, ic_ledger_pb_v1_AccountIdentifier_init_zero, false, ic_ledger_pb_v1_ICPTs_init_zero}
#define ic_ledger_pb_v1_AccountIdentifier_init_zero {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Subaccount_init_zero     {{{NULL}, NULL}}
#define ic_ledger_pb_v1_Memo_init_zero           {0}
#define ic_ledger_pb_v1_TimeStamp_init_zero      {0}
#define ic_ledger_pb_v1_Certification_init_zero  {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ic_ledger_pb_v1_AccountIdentifier_hash_tag 1
#define ic_ledger_pb_v1_ArchiveAddRequest_blocks_tag 1
#define ic_ledger_pb_v1_ArchiveIndexResponse_entries_tag 1
#define ic_ledger_pb_v1_Certification_certification_tag 1
#define ic_ledger_pb_v1_EncodedBlock_block_tag   1
#define ic_ledger_pb_v1_EncodedBlocks_blocks_tag 1
#define ic_ledger_pb_v1_GetNodesResponse_nodes_tag 1
#define ic_ledger_pb_v1_Hash_hash_tag            1
#define ic_ledger_pb_v1_IterBlocksResponse_blocks_tag 1
#define ic_ledger_pb_v1_Subaccount_sub_account_tag 1
#define ic_ledger_pb_v1_TransactionNotificationResponse_response_tag 1
#define ic_ledger_pb_v1_AccountBalanceRequest_account_tag 1
#define ic_ledger_pb_v1_ArchiveIndexEntry_height_from_tag 1
#define ic_ledger_pb_v1_ArchiveIndexEntry_height_to_tag 2
#define ic_ledger_pb_v1_ArchiveIndexEntry_canister_id_tag 3
#define ic_ledger_pb_v1_ArchiveInit_node_max_memory_size_bytes_tag 1
#define ic_ledger_pb_v1_ArchiveInit_max_message_size_bytes_tag 2
#define ic_ledger_pb_v1_BlockHeight_height_tag   1
#define ic_ledger_pb_v1_BlockRequest_block_height_tag 1
#define ic_ledger_pb_v1_BlockResponse_block_tag  1
#define ic_ledger_pb_v1_BlockResponse_canister_id_tag 2
#define ic_ledger_pb_v1_GetBlocksRequest_start_tag 1
#define ic_ledger_pb_v1_GetBlocksRequest_length_tag 2
#define ic_ledger_pb_v1_GetBlocksResponse_blocks_tag 1
#define ic_ledger_pb_v1_GetBlocksResponse_error_tag 2
#define ic_ledger_pb_v1_ICPTs_e8s_tag            1
#define ic_ledger_pb_v1_IterBlocksRequest_start_tag 1
#define ic_ledger_pb_v1_IterBlocksRequest_length_tag 2
#define ic_ledger_pb_v1_LedgerInit_minting_account_tag 1
#define ic_ledger_pb_v1_LedgerInit_initial_values_tag 2
#define ic_ledger_pb_v1_LedgerInit_archive_canister_tag 3
#define ic_ledger_pb_v1_LedgerInit_max_message_size_bytes_tag 4
#define ic_ledger_pb_v1_Memo_memo_tag            1
#define ic_ledger_pb_v1_TimeStamp_timestamp_nanos_tag 1
#define ic_ledger_pb_v1_Account_identifier_tag   1
#define ic_ledger_pb_v1_Account_balance_tag      2
#define ic_ledger_pb_v1_AccountBalanceResponse_balance_tag 1
#define ic_ledger_pb_v1_Burn_from_tag            1
#define ic_ledger_pb_v1_Burn_amount_tag          3
#define ic_ledger_pb_v1_LedgerArchiveRequest_timestamp_tag 1
#define ic_ledger_pb_v1_Mint_to_tag              2
#define ic_ledger_pb_v1_Mint_amount_tag          3
#define ic_ledger_pb_v1_NotifyRequest_block_height_tag 1
#define ic_ledger_pb_v1_NotifyRequest_max_fee_tag 2
#define ic_ledger_pb_v1_NotifyRequest_from_subaccount_tag 3
#define ic_ledger_pb_v1_NotifyRequest_to_canister_tag 4
#define ic_ledger_pb_v1_NotifyRequest_to_subaccount_tag 5
#define ic_ledger_pb_v1_Payment_receiver_gets_tag 1
#define ic_ledger_pb_v1_Refund_refund_tag        2
#define ic_ledger_pb_v1_Refund_error_tag         3
#define ic_ledger_pb_v1_Send_from_tag            1
#define ic_ledger_pb_v1_Send_to_tag              2
#define ic_ledger_pb_v1_Send_amount_tag          3
#define ic_ledger_pb_v1_Send_max_fee_tag         4
#define ic_ledger_pb_v1_SendResponse_resulting_height_tag 1
#define ic_ledger_pb_v1_TipOfChainResponse_certification_tag 1
#define ic_ledger_pb_v1_TipOfChainResponse_chain_length_tag 2
#define ic_ledger_pb_v1_TotalSupplyResponse_total_supply_tag 1
#define ic_ledger_pb_v1_TransactionNotificationRequest_from_tag 1
#define ic_ledger_pb_v1_TransactionNotificationRequest_from_subaccount_tag 2
#define ic_ledger_pb_v1_TransactionNotificationRequest_to_tag 3
#define ic_ledger_pb_v1_TransactionNotificationRequest_to_subaccount_tag 4
#define ic_ledger_pb_v1_TransactionNotificationRequest_block_height_tag 5
#define ic_ledger_pb_v1_TransactionNotificationRequest_amount_tag 6
#define ic_ledger_pb_v1_TransactionNotificationRequest_memo_tag 7
#define ic_ledger_pb_v1_CyclesNotificationResponse_created_canister_id_tag 1
#define ic_ledger_pb_v1_CyclesNotificationResponse_refund_tag 2
#define ic_ledger_pb_v1_CyclesNotificationResponse_topped_up_tag 3
#define ic_ledger_pb_v1_SendRequest_memo_tag     1
#define ic_ledger_pb_v1_SendRequest_payment_tag  2
#define ic_ledger_pb_v1_SendRequest_max_fee_tag  3
#define ic_ledger_pb_v1_SendRequest_from_subaccount_tag 4
#define ic_ledger_pb_v1_SendRequest_to_tag       5
#define ic_ledger_pb_v1_SendRequest_created_at_tag 6
#define ic_ledger_pb_v1_SendRequest_created_at_time_tag 7
#define ic_ledger_pb_v1_Transaction_burn_tag     1
#define ic_ledger_pb_v1_Transaction_mint_tag     2
#define ic_ledger_pb_v1_Transaction_send_tag     3
#define ic_ledger_pb_v1_Transaction_memo_tag     4
#define ic_ledger_pb_v1_Transaction_created_at_tag 5
#define ic_ledger_pb_v1_Transaction_created_at_time_tag 6
#define ic_ledger_pb_v1_Block_parent_hash_tag    1
#define ic_ledger_pb_v1_Block_timestamp_tag      2
#define ic_ledger_pb_v1_Block_transaction_tag    3

/* Struct field encoding specification for nanopb */
#define ic_ledger_pb_v1_LedgerInit_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  minting_account,   1) \
X(a, CALLBACK, REPEATED, MESSAGE,  initial_values,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  archive_canister,   3) \
X(a, STATIC,   SINGULAR, UINT32,   max_message_size_bytes,   4)
#define ic_ledger_pb_v1_LedgerInit_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_LedgerInit_DEFAULT NULL
#define ic_ledger_pb_v1_LedgerInit_minting_account_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_LedgerInit_initial_values_MSGTYPE ic_ledger_pb_v1_Account
#define ic_ledger_pb_v1_LedgerInit_archive_canister_MSGTYPE ic_base_types_pb_v1_PrincipalId

#define ic_ledger_pb_v1_LedgerUpgrade_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_LedgerUpgrade_CALLBACK NULL
#define ic_ledger_pb_v1_LedgerUpgrade_DEFAULT NULL

#define ic_ledger_pb_v1_SendRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memo,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payment,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_fee,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_subaccount,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at_time,   7)
#define ic_ledger_pb_v1_SendRequest_CALLBACK NULL
#define ic_ledger_pb_v1_SendRequest_DEFAULT NULL
#define ic_ledger_pb_v1_SendRequest_memo_MSGTYPE ic_ledger_pb_v1_Memo
#define ic_ledger_pb_v1_SendRequest_payment_MSGTYPE ic_ledger_pb_v1_Payment
#define ic_ledger_pb_v1_SendRequest_max_fee_MSGTYPE ic_ledger_pb_v1_ICPTs
#define ic_ledger_pb_v1_SendRequest_from_subaccount_MSGTYPE ic_ledger_pb_v1_Subaccount
#define ic_ledger_pb_v1_SendRequest_to_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_SendRequest_created_at_MSGTYPE ic_ledger_pb_v1_BlockHeight
#define ic_ledger_pb_v1_SendRequest_created_at_time_MSGTYPE ic_ledger_pb_v1_TimeStamp

#define ic_ledger_pb_v1_SendResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  resulting_height,   1)
#define ic_ledger_pb_v1_SendResponse_CALLBACK NULL
#define ic_ledger_pb_v1_SendResponse_DEFAULT NULL
#define ic_ledger_pb_v1_SendResponse_resulting_height_MSGTYPE ic_ledger_pb_v1_BlockHeight

#define ic_ledger_pb_v1_NotifyRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_height,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_fee,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_subaccount,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to_canister,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to_subaccount,     5)
#define ic_ledger_pb_v1_NotifyRequest_CALLBACK NULL
#define ic_ledger_pb_v1_NotifyRequest_DEFAULT NULL
#define ic_ledger_pb_v1_NotifyRequest_block_height_MSGTYPE ic_ledger_pb_v1_BlockHeight
#define ic_ledger_pb_v1_NotifyRequest_max_fee_MSGTYPE ic_ledger_pb_v1_ICPTs
#define ic_ledger_pb_v1_NotifyRequest_from_subaccount_MSGTYPE ic_ledger_pb_v1_Subaccount
#define ic_ledger_pb_v1_NotifyRequest_to_canister_MSGTYPE ic_base_types_pb_v1_PrincipalId
#define ic_ledger_pb_v1_NotifyRequest_to_subaccount_MSGTYPE ic_ledger_pb_v1_Subaccount

#define ic_ledger_pb_v1_NotifyResponse_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_NotifyResponse_CALLBACK NULL
#define ic_ledger_pb_v1_NotifyResponse_DEFAULT NULL

#define ic_ledger_pb_v1_TransactionNotificationRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from_subaccount,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to_subaccount,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_height,      5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  amount,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memo,              7)
#define ic_ledger_pb_v1_TransactionNotificationRequest_CALLBACK NULL
#define ic_ledger_pb_v1_TransactionNotificationRequest_DEFAULT NULL
#define ic_ledger_pb_v1_TransactionNotificationRequest_from_MSGTYPE ic_base_types_pb_v1_PrincipalId
#define ic_ledger_pb_v1_TransactionNotificationRequest_from_subaccount_MSGTYPE ic_ledger_pb_v1_Subaccount
#define ic_ledger_pb_v1_TransactionNotificationRequest_to_MSGTYPE ic_base_types_pb_v1_PrincipalId
#define ic_ledger_pb_v1_TransactionNotificationRequest_to_subaccount_MSGTYPE ic_ledger_pb_v1_Subaccount
#define ic_ledger_pb_v1_TransactionNotificationRequest_block_height_MSGTYPE ic_ledger_pb_v1_BlockHeight
#define ic_ledger_pb_v1_TransactionNotificationRequest_amount_MSGTYPE ic_ledger_pb_v1_ICPTs
#define ic_ledger_pb_v1_TransactionNotificationRequest_memo_MSGTYPE ic_ledger_pb_v1_Memo

#define ic_ledger_pb_v1_TransactionNotificationResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    response,          1)
#define ic_ledger_pb_v1_TransactionNotificationResponse_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_TransactionNotificationResponse_DEFAULT NULL

#define ic_ledger_pb_v1_CyclesNotificationResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,created_canister_id,response.created_canister_id),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,refund,response.refund),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,topped_up,response.topped_up),   3)
#define ic_ledger_pb_v1_CyclesNotificationResponse_CALLBACK NULL
#define ic_ledger_pb_v1_CyclesNotificationResponse_DEFAULT NULL
#define ic_ledger_pb_v1_CyclesNotificationResponse_response_created_canister_id_MSGTYPE ic_base_types_pb_v1_PrincipalId
#define ic_ledger_pb_v1_CyclesNotificationResponse_response_refund_MSGTYPE ic_ledger_pb_v1_Refund
#define ic_ledger_pb_v1_CyclesNotificationResponse_response_topped_up_MSGTYPE ic_ledger_pb_v1_ToppedUp

#define ic_ledger_pb_v1_AccountBalanceRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  account,           1)
#define ic_ledger_pb_v1_AccountBalanceRequest_CALLBACK NULL
#define ic_ledger_pb_v1_AccountBalanceRequest_DEFAULT NULL
#define ic_ledger_pb_v1_AccountBalanceRequest_account_MSGTYPE ic_ledger_pb_v1_AccountIdentifier

#define ic_ledger_pb_v1_AccountBalanceResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  balance,           1)
#define ic_ledger_pb_v1_AccountBalanceResponse_CALLBACK NULL
#define ic_ledger_pb_v1_AccountBalanceResponse_DEFAULT NULL
#define ic_ledger_pb_v1_AccountBalanceResponse_balance_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_TipOfChainRequest_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_TipOfChainRequest_CALLBACK NULL
#define ic_ledger_pb_v1_TipOfChainRequest_DEFAULT NULL

#define ic_ledger_pb_v1_TipOfChainResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  certification,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chain_length,      2)
#define ic_ledger_pb_v1_TipOfChainResponse_CALLBACK NULL
#define ic_ledger_pb_v1_TipOfChainResponse_DEFAULT NULL
#define ic_ledger_pb_v1_TipOfChainResponse_certification_MSGTYPE ic_ledger_pb_v1_Certification
#define ic_ledger_pb_v1_TipOfChainResponse_chain_length_MSGTYPE ic_ledger_pb_v1_BlockHeight

#define ic_ledger_pb_v1_TotalSupplyRequest_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_TotalSupplyRequest_CALLBACK NULL
#define ic_ledger_pb_v1_TotalSupplyRequest_DEFAULT NULL

#define ic_ledger_pb_v1_TotalSupplyResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  total_supply,      1)
#define ic_ledger_pb_v1_TotalSupplyResponse_CALLBACK NULL
#define ic_ledger_pb_v1_TotalSupplyResponse_DEFAULT NULL
#define ic_ledger_pb_v1_TotalSupplyResponse_total_supply_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_LedgerArchiveRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         1)
#define ic_ledger_pb_v1_LedgerArchiveRequest_CALLBACK NULL
#define ic_ledger_pb_v1_LedgerArchiveRequest_DEFAULT NULL
#define ic_ledger_pb_v1_LedgerArchiveRequest_timestamp_MSGTYPE ic_ledger_pb_v1_TimeStamp

#define ic_ledger_pb_v1_BlockRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   block_height,      1)
#define ic_ledger_pb_v1_BlockRequest_CALLBACK NULL
#define ic_ledger_pb_v1_BlockRequest_DEFAULT NULL

#define ic_ledger_pb_v1_EncodedBlock_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    block,             1)
#define ic_ledger_pb_v1_EncodedBlock_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_EncodedBlock_DEFAULT NULL

#define ic_ledger_pb_v1_BlockResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (block_content,block,block_content.block),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (block_content,canister_id,block_content.canister_id),   2)
#define ic_ledger_pb_v1_BlockResponse_CALLBACK NULL
#define ic_ledger_pb_v1_BlockResponse_DEFAULT NULL
#define ic_ledger_pb_v1_BlockResponse_block_content_block_MSGTYPE ic_ledger_pb_v1_EncodedBlock
#define ic_ledger_pb_v1_BlockResponse_block_content_canister_id_MSGTYPE ic_base_types_pb_v1_PrincipalId

#define ic_ledger_pb_v1_GetBlocksRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start,             1) \
X(a, STATIC,   SINGULAR, UINT64,   length,            2)
#define ic_ledger_pb_v1_GetBlocksRequest_CALLBACK NULL
#define ic_ledger_pb_v1_GetBlocksRequest_DEFAULT NULL

#define ic_ledger_pb_v1_Refund_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  refund,            2) \
X(a, CALLBACK, SINGULAR, STRING,   error,             3)
#define ic_ledger_pb_v1_Refund_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_Refund_DEFAULT NULL
#define ic_ledger_pb_v1_Refund_refund_MSGTYPE ic_ledger_pb_v1_BlockHeight

#define ic_ledger_pb_v1_ToppedUp_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_ToppedUp_CALLBACK NULL
#define ic_ledger_pb_v1_ToppedUp_DEFAULT NULL

#define ic_ledger_pb_v1_EncodedBlocks_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            1)
#define ic_ledger_pb_v1_EncodedBlocks_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_EncodedBlocks_DEFAULT NULL
#define ic_ledger_pb_v1_EncodedBlocks_blocks_MSGTYPE ic_ledger_pb_v1_EncodedBlock

#define ic_ledger_pb_v1_GetBlocksResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (get_blocks_content,blocks,get_blocks_content.blocks),   1) \
X(a, CALLBACK, ONEOF,    STRING,   (get_blocks_content,error,get_blocks_content.error),   2)
#define ic_ledger_pb_v1_GetBlocksResponse_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_GetBlocksResponse_DEFAULT NULL
#define ic_ledger_pb_v1_GetBlocksResponse_get_blocks_content_blocks_MSGTYPE ic_ledger_pb_v1_EncodedBlocks

#define ic_ledger_pb_v1_IterBlocksRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   start,             1) \
X(a, STATIC,   SINGULAR, UINT64,   length,            2)
#define ic_ledger_pb_v1_IterBlocksRequest_CALLBACK NULL
#define ic_ledger_pb_v1_IterBlocksRequest_DEFAULT NULL

#define ic_ledger_pb_v1_IterBlocksResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            1)
#define ic_ledger_pb_v1_IterBlocksResponse_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_IterBlocksResponse_DEFAULT NULL
#define ic_ledger_pb_v1_IterBlocksResponse_blocks_MSGTYPE ic_ledger_pb_v1_EncodedBlock

#define ic_ledger_pb_v1_ArchiveIndexEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   height_from,       1) \
X(a, STATIC,   SINGULAR, UINT64,   height_to,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  canister_id,       3)
#define ic_ledger_pb_v1_ArchiveIndexEntry_CALLBACK NULL
#define ic_ledger_pb_v1_ArchiveIndexEntry_DEFAULT NULL
#define ic_ledger_pb_v1_ArchiveIndexEntry_canister_id_MSGTYPE ic_base_types_pb_v1_PrincipalId

#define ic_ledger_pb_v1_ArchiveIndexResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1)
#define ic_ledger_pb_v1_ArchiveIndexResponse_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_ArchiveIndexResponse_DEFAULT NULL
#define ic_ledger_pb_v1_ArchiveIndexResponse_entries_MSGTYPE ic_ledger_pb_v1_ArchiveIndexEntry

#define ic_ledger_pb_v1_ArchiveInit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   node_max_memory_size_bytes,   1) \
X(a, STATIC,   SINGULAR, UINT32,   max_message_size_bytes,   2)
#define ic_ledger_pb_v1_ArchiveInit_CALLBACK NULL
#define ic_ledger_pb_v1_ArchiveInit_DEFAULT NULL

#define ic_ledger_pb_v1_ArchiveAddRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            1)
#define ic_ledger_pb_v1_ArchiveAddRequest_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_ArchiveAddRequest_DEFAULT NULL
#define ic_ledger_pb_v1_ArchiveAddRequest_blocks_MSGTYPE ic_ledger_pb_v1_Block

#define ic_ledger_pb_v1_ArchiveAddResponse_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_ArchiveAddResponse_CALLBACK NULL
#define ic_ledger_pb_v1_ArchiveAddResponse_DEFAULT NULL

#define ic_ledger_pb_v1_GetNodesRequest_FIELDLIST(X, a) \

#define ic_ledger_pb_v1_GetNodesRequest_CALLBACK NULL
#define ic_ledger_pb_v1_GetNodesRequest_DEFAULT NULL

#define ic_ledger_pb_v1_GetNodesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  nodes,             1)
#define ic_ledger_pb_v1_GetNodesResponse_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_GetNodesResponse_DEFAULT NULL
#define ic_ledger_pb_v1_GetNodesResponse_nodes_MSGTYPE ic_base_types_pb_v1_PrincipalId

#define ic_ledger_pb_v1_ICPTs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   e8s,               1)
#define ic_ledger_pb_v1_ICPTs_CALLBACK NULL
#define ic_ledger_pb_v1_ICPTs_DEFAULT NULL

#define ic_ledger_pb_v1_Payment_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receiver_gets,     1)
#define ic_ledger_pb_v1_Payment_CALLBACK NULL
#define ic_ledger_pb_v1_Payment_DEFAULT NULL
#define ic_ledger_pb_v1_Payment_receiver_gets_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_BlockHeight_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   height,            1)
#define ic_ledger_pb_v1_BlockHeight_CALLBACK NULL
#define ic_ledger_pb_v1_BlockHeight_DEFAULT NULL

#define ic_ledger_pb_v1_Block_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parent_hash,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       3)
#define ic_ledger_pb_v1_Block_CALLBACK NULL
#define ic_ledger_pb_v1_Block_DEFAULT NULL
#define ic_ledger_pb_v1_Block_parent_hash_MSGTYPE ic_ledger_pb_v1_Hash
#define ic_ledger_pb_v1_Block_timestamp_MSGTYPE ic_ledger_pb_v1_TimeStamp
#define ic_ledger_pb_v1_Block_transaction_MSGTYPE ic_ledger_pb_v1_Transaction

#define ic_ledger_pb_v1_Hash_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    hash,              1)
#define ic_ledger_pb_v1_Hash_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_Hash_DEFAULT NULL

#define ic_ledger_pb_v1_Account_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  identifier,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  balance,           2)
#define ic_ledger_pb_v1_Account_CALLBACK NULL
#define ic_ledger_pb_v1_Account_DEFAULT NULL
#define ic_ledger_pb_v1_Account_identifier_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_Account_balance_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_Transaction_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transfer,burn,transfer.burn),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transfer,mint,transfer.mint),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (transfer,send,transfer.send),   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  memo,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at_time,   6)
#define ic_ledger_pb_v1_Transaction_CALLBACK NULL
#define ic_ledger_pb_v1_Transaction_DEFAULT NULL
#define ic_ledger_pb_v1_Transaction_transfer_burn_MSGTYPE ic_ledger_pb_v1_Burn
#define ic_ledger_pb_v1_Transaction_transfer_mint_MSGTYPE ic_ledger_pb_v1_Mint
#define ic_ledger_pb_v1_Transaction_transfer_send_MSGTYPE ic_ledger_pb_v1_Send
#define ic_ledger_pb_v1_Transaction_memo_MSGTYPE ic_ledger_pb_v1_Memo
#define ic_ledger_pb_v1_Transaction_created_at_MSGTYPE ic_ledger_pb_v1_BlockHeight
#define ic_ledger_pb_v1_Transaction_created_at_time_MSGTYPE ic_ledger_pb_v1_TimeStamp

#define ic_ledger_pb_v1_Send_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  amount,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  max_fee,           4)
#define ic_ledger_pb_v1_Send_CALLBACK NULL
#define ic_ledger_pb_v1_Send_DEFAULT NULL
#define ic_ledger_pb_v1_Send_from_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_Send_to_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_Send_amount_MSGTYPE ic_ledger_pb_v1_ICPTs
#define ic_ledger_pb_v1_Send_max_fee_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_Mint_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  to,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  amount,            3)
#define ic_ledger_pb_v1_Mint_CALLBACK NULL
#define ic_ledger_pb_v1_Mint_DEFAULT NULL
#define ic_ledger_pb_v1_Mint_to_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_Mint_amount_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_Burn_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  from,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  amount,            3)
#define ic_ledger_pb_v1_Burn_CALLBACK NULL
#define ic_ledger_pb_v1_Burn_DEFAULT NULL
#define ic_ledger_pb_v1_Burn_from_MSGTYPE ic_ledger_pb_v1_AccountIdentifier
#define ic_ledger_pb_v1_Burn_amount_MSGTYPE ic_ledger_pb_v1_ICPTs

#define ic_ledger_pb_v1_AccountIdentifier_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    hash,              1)
#define ic_ledger_pb_v1_AccountIdentifier_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_AccountIdentifier_DEFAULT NULL

#define ic_ledger_pb_v1_Subaccount_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    sub_account,       1)
#define ic_ledger_pb_v1_Subaccount_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_Subaccount_DEFAULT NULL

#define ic_ledger_pb_v1_Memo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   memo,              1)
#define ic_ledger_pb_v1_Memo_CALLBACK NULL
#define ic_ledger_pb_v1_Memo_DEFAULT NULL

#define ic_ledger_pb_v1_TimeStamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_nanos,   1)
#define ic_ledger_pb_v1_TimeStamp_CALLBACK NULL
#define ic_ledger_pb_v1_TimeStamp_DEFAULT NULL

#define ic_ledger_pb_v1_Certification_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    certification,     1)
#define ic_ledger_pb_v1_Certification_CALLBACK pb_default_field_callback
#define ic_ledger_pb_v1_Certification_DEFAULT NULL

extern const pb_msgdesc_t ic_ledger_pb_v1_LedgerInit_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_LedgerUpgrade_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_SendRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_SendResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_NotifyRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_NotifyResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TransactionNotificationRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TransactionNotificationResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_CyclesNotificationResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_AccountBalanceRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_AccountBalanceResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TipOfChainRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TipOfChainResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TotalSupplyRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TotalSupplyResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_LedgerArchiveRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_BlockRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_EncodedBlock_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_BlockResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_GetBlocksRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Refund_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ToppedUp_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_EncodedBlocks_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_GetBlocksResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_IterBlocksRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_IterBlocksResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ArchiveIndexEntry_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ArchiveIndexResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ArchiveInit_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ArchiveAddRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ArchiveAddResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_GetNodesRequest_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_GetNodesResponse_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_ICPTs_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Payment_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_BlockHeight_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Block_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Hash_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Account_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Transaction_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Send_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Mint_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Burn_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_AccountIdentifier_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Subaccount_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Memo_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_TimeStamp_msg;
extern const pb_msgdesc_t ic_ledger_pb_v1_Certification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ic_ledger_pb_v1_LedgerInit_fields &ic_ledger_pb_v1_LedgerInit_msg
#define ic_ledger_pb_v1_LedgerUpgrade_fields &ic_ledger_pb_v1_LedgerUpgrade_msg
#define ic_ledger_pb_v1_SendRequest_fields &ic_ledger_pb_v1_SendRequest_msg
#define ic_ledger_pb_v1_SendResponse_fields &ic_ledger_pb_v1_SendResponse_msg
#define ic_ledger_pb_v1_NotifyRequest_fields &ic_ledger_pb_v1_NotifyRequest_msg
#define ic_ledger_pb_v1_NotifyResponse_fields &ic_ledger_pb_v1_NotifyResponse_msg
#define ic_ledger_pb_v1_TransactionNotificationRequest_fields &ic_ledger_pb_v1_TransactionNotificationRequest_msg
#define ic_ledger_pb_v1_TransactionNotificationResponse_fields &ic_ledger_pb_v1_TransactionNotificationResponse_msg
#define ic_ledger_pb_v1_CyclesNotificationResponse_fields &ic_ledger_pb_v1_CyclesNotificationResponse_msg
#define ic_ledger_pb_v1_AccountBalanceRequest_fields &ic_ledger_pb_v1_AccountBalanceRequest_msg
#define ic_ledger_pb_v1_AccountBalanceResponse_fields &ic_ledger_pb_v1_AccountBalanceResponse_msg
#define ic_ledger_pb_v1_TipOfChainRequest_fields &ic_ledger_pb_v1_TipOfChainRequest_msg
#define ic_ledger_pb_v1_TipOfChainResponse_fields &ic_ledger_pb_v1_TipOfChainResponse_msg
#define ic_ledger_pb_v1_TotalSupplyRequest_fields &ic_ledger_pb_v1_TotalSupplyRequest_msg
#define ic_ledger_pb_v1_TotalSupplyResponse_fields &ic_ledger_pb_v1_TotalSupplyResponse_msg
#define ic_ledger_pb_v1_LedgerArchiveRequest_fields &ic_ledger_pb_v1_LedgerArchiveRequest_msg
#define ic_ledger_pb_v1_BlockRequest_fields &ic_ledger_pb_v1_BlockRequest_msg
#define ic_ledger_pb_v1_EncodedBlock_fields &ic_ledger_pb_v1_EncodedBlock_msg
#define ic_ledger_pb_v1_BlockResponse_fields &ic_ledger_pb_v1_BlockResponse_msg
#define ic_ledger_pb_v1_GetBlocksRequest_fields &ic_ledger_pb_v1_GetBlocksRequest_msg
#define ic_ledger_pb_v1_Refund_fields &ic_ledger_pb_v1_Refund_msg
#define ic_ledger_pb_v1_ToppedUp_fields &ic_ledger_pb_v1_ToppedUp_msg
#define ic_ledger_pb_v1_EncodedBlocks_fields &ic_ledger_pb_v1_EncodedBlocks_msg
#define ic_ledger_pb_v1_GetBlocksResponse_fields &ic_ledger_pb_v1_GetBlocksResponse_msg
#define ic_ledger_pb_v1_IterBlocksRequest_fields &ic_ledger_pb_v1_IterBlocksRequest_msg
#define ic_ledger_pb_v1_IterBlocksResponse_fields &ic_ledger_pb_v1_IterBlocksResponse_msg
#define ic_ledger_pb_v1_ArchiveIndexEntry_fields &ic_ledger_pb_v1_ArchiveIndexEntry_msg
#define ic_ledger_pb_v1_ArchiveIndexResponse_fields &ic_ledger_pb_v1_ArchiveIndexResponse_msg
#define ic_ledger_pb_v1_ArchiveInit_fields &ic_ledger_pb_v1_ArchiveInit_msg
#define ic_ledger_pb_v1_ArchiveAddRequest_fields &ic_ledger_pb_v1_ArchiveAddRequest_msg
#define ic_ledger_pb_v1_ArchiveAddResponse_fields &ic_ledger_pb_v1_ArchiveAddResponse_msg
#define ic_ledger_pb_v1_GetNodesRequest_fields &ic_ledger_pb_v1_GetNodesRequest_msg
#define ic_ledger_pb_v1_GetNodesResponse_fields &ic_ledger_pb_v1_GetNodesResponse_msg
#define ic_ledger_pb_v1_ICPTs_fields &ic_ledger_pb_v1_ICPTs_msg
#define ic_ledger_pb_v1_Payment_fields &ic_ledger_pb_v1_Payment_msg
#define ic_ledger_pb_v1_BlockHeight_fields &ic_ledger_pb_v1_BlockHeight_msg
#define ic_ledger_pb_v1_Block_fields &ic_ledger_pb_v1_Block_msg
#define ic_ledger_pb_v1_Hash_fields &ic_ledger_pb_v1_Hash_msg
#define ic_ledger_pb_v1_Account_fields &ic_ledger_pb_v1_Account_msg
#define ic_ledger_pb_v1_Transaction_fields &ic_ledger_pb_v1_Transaction_msg
#define ic_ledger_pb_v1_Send_fields &ic_ledger_pb_v1_Send_msg
#define ic_ledger_pb_v1_Mint_fields &ic_ledger_pb_v1_Mint_msg
#define ic_ledger_pb_v1_Burn_fields &ic_ledger_pb_v1_Burn_msg
#define ic_ledger_pb_v1_AccountIdentifier_fields &ic_ledger_pb_v1_AccountIdentifier_msg
#define ic_ledger_pb_v1_Subaccount_fields &ic_ledger_pb_v1_Subaccount_msg
#define ic_ledger_pb_v1_Memo_fields &ic_ledger_pb_v1_Memo_msg
#define ic_ledger_pb_v1_TimeStamp_fields &ic_ledger_pb_v1_TimeStamp_msg
#define ic_ledger_pb_v1_Certification_fields &ic_ledger_pb_v1_Certification_msg

/* Maximum encoded size of messages (where known) */
/* ic_ledger_pb_v1_LedgerInit_size depends on runtime parameters */
/* ic_ledger_pb_v1_SendRequest_size depends on runtime parameters */
/* ic_ledger_pb_v1_NotifyRequest_size depends on runtime parameters */
/* ic_ledger_pb_v1_TransactionNotificationRequest_size depends on runtime parameters */
/* ic_ledger_pb_v1_TransactionNotificationResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_CyclesNotificationResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_AccountBalanceRequest_size depends on runtime parameters */
/* ic_ledger_pb_v1_TipOfChainResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_EncodedBlock_size depends on runtime parameters */
/* ic_ledger_pb_v1_BlockResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_Refund_size depends on runtime parameters */
/* ic_ledger_pb_v1_EncodedBlocks_size depends on runtime parameters */
/* ic_ledger_pb_v1_GetBlocksResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_IterBlocksResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_ArchiveIndexResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_ArchiveAddRequest_size depends on runtime parameters */
/* ic_ledger_pb_v1_GetNodesResponse_size depends on runtime parameters */
/* ic_ledger_pb_v1_Block_size depends on runtime parameters */
/* ic_ledger_pb_v1_Hash_size depends on runtime parameters */
/* ic_ledger_pb_v1_Account_size depends on runtime parameters */
/* ic_ledger_pb_v1_Transaction_size depends on runtime parameters */
/* ic_ledger_pb_v1_Send_size depends on runtime parameters */
/* ic_ledger_pb_v1_Mint_size depends on runtime parameters */
/* ic_ledger_pb_v1_Burn_size depends on runtime parameters */
/* ic_ledger_pb_v1_AccountIdentifier_size depends on runtime parameters */
/* ic_ledger_pb_v1_Subaccount_size depends on runtime parameters */
/* ic_ledger_pb_v1_Certification_size depends on runtime parameters */
#define ic_ledger_pb_v1_AccountBalanceResponse_size 13
#define ic_ledger_pb_v1_ArchiveAddResponse_size  0
#define ic_ledger_pb_v1_ArchiveInit_size         12
#define ic_ledger_pb_v1_BlockHeight_size         11
#define ic_ledger_pb_v1_BlockRequest_size        11
#define ic_ledger_pb_v1_GetBlocksRequest_size    22
#define ic_ledger_pb_v1_GetNodesRequest_size     0
#define ic_ledger_pb_v1_ICPTs_size               11
#define ic_ledger_pb_v1_IterBlocksRequest_size   22
#define ic_ledger_pb_v1_LedgerArchiveRequest_size 13
#define ic_ledger_pb_v1_LedgerUpgrade_size       0
#define ic_ledger_pb_v1_Memo_size                11
#define ic_ledger_pb_v1_NotifyResponse_size      0
#define ic_ledger_pb_v1_Payment_size             13
#define ic_ledger_pb_v1_SendResponse_size        13
#define ic_ledger_pb_v1_TimeStamp_size           11
#define ic_ledger_pb_v1_TipOfChainRequest_size   0
#define ic_ledger_pb_v1_ToppedUp_size            0
#define ic_ledger_pb_v1_TotalSupplyRequest_size  0
#define ic_ledger_pb_v1_TotalSupplyResponse_size 13
#if defined(ic_base_types_pb_v1_PrincipalId_size)
#define ic_ledger_pb_v1_ArchiveIndexEntry_size   (28 + ic_base_types_pb_v1_PrincipalId_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
