[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "rslib"
version = "0.1.0"
edition = "2021"
readme = "README.md"
resolver = "2"

[lib]
name = "rslib"
crate-type = ["staticlib"]

[dependencies]
no-std-compat = { version = "0.4.1" }
bls_signature = { git = "https://github.com/dfinity/verify-bls-signatures.git", revision = "c2d3442100f2ca526084df8f7c58dfa125bf54bd", package = "ic-verify-bls-signature", default-features = false }

[dev-dependencies]
no-std-compat = { version = "0.4.1", features = ["std"] }
serde_json = "1.0.56"
hex = { version = "0.4" }
serde-json-core = { version = "0.4.0", features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.9.1", default-features = false }
base64 = { version = "0.13.0" }


[target.'cfg(fuzzing)'.dependencies]
no-std-compat = { version = "0.4.1", features = ["std"] }

[profile.release]
lto = false
codegen-units = 1
debug = false
opt-level = "z"

[profile.dev]
panic = "abort"

[patch.crates-io]
# Patch the bls12_381 crate which is a dependency of the verify-bls-signatures, 
# it contains important PIC and Stack issues.
bls12_381 = { git = "https://github.com/Zondax/bls12_381.git", branch = "ledger" }
