name: Verify PRs to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - master
      - dev

jobs:
  ledger-check-version:
    uses: Zondax/_workflows/.github/workflows/_ledger_check_version.yml@ledger/ci
    with:
      runs-on: ${{ github.repository_owner == 'zondax' && 'zondax-runners' || 'ubuntu-latest' }}
