name: Lint and format 💅

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
      - develop
      - master
      - dev

jobs:
  ledger-lint:
    uses: Zondax/_workflows/.github/workflows/_ledger_lint.yml@fix/lint
    with:
      runs-on: ${{ github.repository_owner == 'zondax' && 'zondax-runners' || 'ubuntu-latest' }}
      check_rust: true
