name: "Test/Build"
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          make deps
          brew install conan
          conan config install https://github.com/conan-io/conanclientcert.git
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_ledger:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: zondax/builder-bolos:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      BOLOS_SDK: ${{ github.workspace }}/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
      HOME: /home/zondax_circle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Standard app
        shell: bash -l {0}
        run: |
          source $HOME/.cargo/env
          make

  test_zemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - name: Install rust
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake binutils-dev libiberty-dev libelf-dev libdw-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install yarn
        run: |
          npm install -g yarn
      - name: Build Ledger app
        run: |
          make
      - name: Build/Install build js deps
        run: |
          export PATH=~/.cargo/bin:$PATH
          make zemu_install
      - name: Run zemu tests
        run: |
          export PATH=~/.cargo/bin:$PATH
          make zemu_test

  build_package:
    needs: [ configure, build, build_ledger, test_zemu ]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/builder-bolos:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      BOLOS_SDK: ${{ github.workspace }}/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
      HOME: /home/zondax_circle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        shell: bash -l {0}
        run: |
          source $HOME/.cargo/env
          make
      - name: Set tag name var
        id: vars
        run: |
          pip install ledgerblue
          echo ::set-output name=tag_name::$(./app/pkg/installer_s.sh version)
      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: ./app/pkg/installer_s.sh
          tag_name: ${{ steps.vars.outputs.tag_name }}
          draft: false
          prerelease: false
